image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      cp -r /home/gitpod/phase_install ./phase_install
      pip install -r requirements.txt
      mkdir build && cd build
      cmake -DPhase_DIR="./phase_install/lib/cmake" ..
      make -j$(nproc)

github:
  prebuilds:
    # prebuilds disabled untill dockerfile created for system installs

    # enable for the default branch (defaults to true)
    main: false
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: false
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: false
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false
