image: gitpod/workspace-full

tasks:
  - init: |
      mkdir phase_install
      curl --output phase-v0.1.2-2-ubuntu-20.04-x86_64.tar.gz -L https://github.com/i3drobotics/phase/releases/download/v0.1.2-2/phase-v0.1.2-2-ubuntu-20.04-x86_64.tar.gz
      tar -xf phase-v0.1.2-2-ubuntu-20.04-x86_64.tar.gz -C ./phase_install
      sudo apt update
      sudo apt install -y libavcodec-dev libavformat-dev libswscale-dev
      sudo apt install -y libgl-dev liblapack-dev libblas-dev libgtk2.0-dev
      sudo apt install -y libgstreamer1.0-0 libgstreamer-plugins-base1.0-0
      sudo apt install -y zlib1g libstdc++6
      sudo apt install -y libc6 libgcc1
      pip install -r requirements.txt
      mkdir build && cd build
      cmake -DPhase_DIR="./phase_install/lib/cmake" ..
      make -j$(nproc)

github:
  prebuilds:
    # prebuilds disabled untill dockerfile created for system installs

    # enable for the default branch (defaults to true)
    main: false
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: false
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: false
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false
